
services:
  nestar-hotel:
    container_name: nestar-hotel
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/nestar-hotel
    working_dir: /usr/src/nestar-hotel

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge


  # docker compose up -d
  # docker compose start
  # docker compose restart
  # docker compose stop && docker compose rm -f
  # docker compose config
